name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - tdoan

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: daviseraaa
          password: Trantuandoan123@

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Đảm bảo Dockerfile của bạn có tên là Dockerfile và nằm ở thư mục gốc
          push: true          # Đẩy image lên Docker Hub sau khi build
          tags: daviseraaa/eCommerce-server:latest