name: Next Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/services/BTL-web
            git fetch origin
            git checkout production
            git pull
            docker build -t btlweb .
            docker stop btlweb || true
            docker rm btlweb-container || true
            docker run -d --name btlweb-container -p 4000:3000 btlweb
